name: Create Scratch Org

on:
  create:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install salesforce CLI
        run: npm install sfdx-cli npx

      - name: Populate auth file with DEVHUB_SFDX_URL secret
      run: echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt

      - name: Authenticate Dev Hub
      run: sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d

      - name: Create scratch org
      run:'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1


      - name: Handle fail
        if: ${{ always() }}
        run: |
          npx sfdx force:org:delete -p
